import os

from dotenv import load_dotenv

load_dotenv()

AWAITERCONFIG_TIMEOUT = os.getenv('AWAITERCONFIG_TIMEOUT')
AWAITERCONFIG_POLLINGINTERVAL = os.getenv('AWAITERCONFIG_POLLINGINTERVAL')
AWAITERCONFIG_IMPLICITWAIT = os.getenv('AWAITERCONFIG_IMPLICITWAIT')
AWAITERCONFIG_ASYNCHRONOUSJAVASCRIPT = os.getenv('AWAITERCONFIG_ASYNCHRONOUSJAVASCRIPT')
AWAITERCONFIG_PAGELOAD = os.getenv('AWAITERCONFIG_PAGELOAD')

BROWSEROPTIONSCONFIG_ARGUMENTS = os.getenv('BROWSEROPTIONSCONFIG_ARGUMENTS')

NAVIGATION_CONFIG_BASEURL = os.getenv('NAVIGATION_CONFIG_BASEURL')
NAVIGATION_CONFIG_HOMEPAGEROUTE = os.getenv('NAVIGATION_CONFIG_HOMEPAGEROUTE')

REMOTEBROWSER_CONFIG_BROWSERNAME = os.getenv('REMOTEBROWSER_CONFIG_BROWSERNAME')
REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_USERNAME = os.getenv('REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_USERNAME')
REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_ACCESSKEY = os.getenv('REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_ACCESSKEY')
REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_LOCAL = os.getenv('REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_LOCAL')
REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_OS = os.getenv('REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_OS')
REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_OS_VERSION = os.getenv('REMOTEBROWSER_CONFIG_BROWSERSTACKOPTIONS_OS_VERSION')
REMOTEBROWSER_CONFIG_BROWSER_VERSION = os.getenv('REMOTEBROWSER_CONFIG_BROWSER_VERSION')
REMOTEBROWSER_CONFIG_PLATFORM_NAME = os.getenv('REMOTEBROWSER_CONFIG_PLATFORM_NAME')
REMOTEBROWSER_CONFIG_SELENIUM_GRID_URL = os.getenv('REMOTEBROWSER_CONFIG_SELENIUM_GRID_URL')
REMOTEBROWSER_CONFIG_USE_SELENIUM_GRID = os.getenv('REMOTEBROWSER_CONFIG_USE_SELENIUM_GRID')
